apiVersion: v2
name: helm-project-operator
description: Helm Project Operator
version: 9.9.9-dev
appVersion: 9.9.9-dev
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Helm Project Operator
  catalog.cattle.io/kube-version: '>=1.16.0-0'
  catalog.cattle.io/namespace: cattle-helm-system
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/provides-gvr: helm.cattle.io.projecthelmchart/v1alpha1
  catalog.cattle.io/rancher-version: '>= 2.6.0-0'
  catalog.cattle.io/release-name: helm-project-operator
  catalog.cattle.io/os: linux,windows
maintainers:
  - email: dan.pock@suse.com
    name: Dan Pock
